version: "3.9"
services:
  stashaway-backend:
    build:
      context: ./
      target: dev
    ports:
      - '${APP_PORT:-3001}:3001'
    volumes:
      - .:/src
    command: npm run dev
    environment:
      NODE_ENV: development
      DEBUG: 'nodejs-docker-express: *'
    networks:
      - shared-network
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_DATABASE: stashawayDB
    ports:
      - '${FORWARD_DB_PORT:-27071}:27071'
    volumes:
      - 'mongo-volume:/data/db'
    networks:
      - shared-network
    command: mongod
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - shared-network
networks:
  shared-network:
    name: stashaway-network
    driver: bridge
volumes:
  mongo-volume:
    driver: local
