version: "3.9"
services:
  stashaway-backend:
    build:
      context: ./
      target: dev
    ports:
      - '${APP_PORT:-3001}:3001'
    volumes:
      - .:/src
    command: npm run dev
    environment:
      NODE_ENV: development
      DEBUG: 'nodejs-docker-express: *'
    networks:
      - shared-network
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_DATABASE: stashawayDB
    ports:
      - '${FORWARD_DB_PORT:-27017}:27017'
    volumes:
      - 'mongo-volume:/data/db'
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - shared-network
    command: 'mongod --bind_ip_all --replSet rs0'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/stashawayDB
    networks:
      - shared-network
networks:
  shared-network:
    name: stashaway-network
    driver: bridge
volumes:
  mongo-volume:
    driver: local
